/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mo.automatictextdetection;

import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class AutomaticTextDetectionAnalysisConfigDialog extends javax.swing.JDialog {

    
    public AutomaticTextDetectionAnalysisConfigDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AutomaticTextDetectionAnalysisConfigDialog() {
        super(null, "configuracion de analisis", ModalityType.APPLICATION_MODAL);
         this.setLocationRelativeTo(null);
         initComponents();
         this.setLocationRelativeTo(null);
         this.configurationName = null;
         this.setVisible(true);
         //this.accepted = false;

        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceptButtton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        configurationNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        acceptButtton.setText("Aceptar");
        acceptButtton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButttonMouseClicked(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        configurationNameField.setText("Nombre Configuracion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configurationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptButtton)
                        .addGap(29, 29, 29)
                        .addComponent(cancelButton)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(configurationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButtton)
                    .addComponent(cancelButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButttonMouseClicked
            this.accepted = true;
            this.configurationName = this.configurationNameField.getText();
            this.dispose();
    }//GEN-LAST:event_acceptButttonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
            this.accepted =  false;
            this.configurationName =  null;
            this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    
    public boolean showDialog() {
        return this.accepted;
    }
    
    public String  getConfigurationName(){
        return this.configurationName;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButtton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField configurationNameField;
    // End of variables declaration//GEN-END:variables
    private String configurationName;
    private boolean accepted;

}
